import dotenv from "dotenv";

dotenv.config();

interface IConfig {
  APP_PORT: string | number;
  APP_HOST: string;

  MONGO_URI: string;

  JWT_ACCESS_SECRET: string;
  JWT_REFRESH_SECRET: string;
  JWT_ACCESS_EXPIRATION: any;
  JWT_REFRESH_EXPIRATION: any;

  ACTION_FORGOT_PASSWORD_SECRET: string;
  ACTION_FORGOT_PASSWORD_EXPIRATION: string;
  ACTION_VERIFY_EMAIL_SECRET: string;
  ACTION_VERIFY_EMAIL_EXPIRATION: string;

  SMTP_EMAIL: string;
  SMTP_PASSWORD: string;

  FRONTEND_URL: string;

  AWS_ACCESS_KEY: string;
  AWS_SECRET_KEY: string;
  AWS_S3_BUCKET_NAME: string;
  AWS_S3_REGION: string;
  AWS_S3_ENDPOINT: string;
}

export const config: IConfig = {
  APP_PORT: process.env.APP_PORT || 3001,
  APP_HOST: process.env.APP_HOST,

  MONGO_URI: process.env.MONGO_URI,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRATION: process.env.JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRATION: process.env.JWT_REFRESH_EXPIRATION,

  ACTION_FORGOT_PASSWORD_SECRET: process.env.ACTION_FORGOT_PASSWORD_SECRET,
  ACTION_FORGOT_PASSWORD_EXPIRATION:
    process.env.ACTION_FORGOT_PASSWORD_EXPIRATION,
  ACTION_VERIFY_EMAIL_SECRET: process.env.ACTION_VERIFY_EMAIL_SECRET,
  ACTION_VERIFY_EMAIL_EXPIRATION: process.env.ACTION_VERIFY_EMAIL_EXPIRATION,

  SMTP_EMAIL: process.env.SMTP_EMAIL,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,

  FRONTEND_URL: process.env.FRONTEND_URL,

  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: process.env.AWS_S3_REGION,
  AWS_S3_ENDPOINT: process.env.AWS_S3_ENDPOINT,
};
